import { faker } from '@faker-js/faker';

export const countries = {
  europa: {
    title: 'Europa',
    banner: faker.image.city(1234, 2345, true),
    description: 'A Europa é, por convenção, um dos seis continentes do mundo. Compreendendo a península ocidental da Eurásia, a Europa geralmente divide-se da Ásia a leste pela divisória de águas dos montes Urais, o rio Ural, o mar Cáspio, o Cáucaso, e o mar Negro a sudeste',
    countries: 50,
    languages: 60,
    city: 27,
    cities: [{
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    }],
  },
  americaNorte: {
    title: 'América do Norte',
    banner: faker.image.city(1234, 2345, true),
    description: faker.random.words(20),
    countries: faker.datatype.number(),
    languages: faker.datatype.number(),
    city: faker.datatype.number(),
    cities: [{
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    ],
  },
  americaSul: {
    title: 'América do Sul',
    banner: faker.image.city(1234, 2345, true),
    description: faker.random.words(20),
    countries: faker.datatype.number(),
    languages: faker.datatype.number(),
    city: faker.datatype.number(),
    cities: [{
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    ],
  },
  asia: {
    title: 'Ásia',
    banner: faker.image.city(1234, 2345, true),
    description: faker.random.words(20),
    countries: faker.datatype.number(),
    languages: faker.datatype.number(),
    city: faker.datatype.number(),
    cities: [{
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    ],
  },
  oceania: {
    title: 'Oceania',
    banner: faker.image.city(1234, 2345, true),
    description: faker.random.words(20),
    countries: faker.datatype.number(),
    languages: faker.datatype.number(),
    city: faker.datatype.number(),
    cities: [{
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    ],
  },
  africa: {
    title: 'África',
    banner: faker.image.city(1234, 2345, true),
    description: faker.random.words(20),
    countries: faker.datatype.number(),
    languages: faker.datatype.number(),
    city: faker.datatype.number(),
    cities: [{
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    {
      image: faker.image.city(1234, 2345, true),
      name: faker.random.word(),
      capital: faker.random.word(),
      flag: faker.image.abstract(),
    },
    ],
  },
};
